### ISSUE TITLE
Hi, I wanna ask something about the sentiment labels on Sentiment Classfication!

### ISSUE THREAD

**Issue by KuzmaNg** [A2Zadeh/CMU-MultimodalDataSDK#18]
Thanks for all the efforts made by your group. Here, I got some questions after running the TFN network provided by Justin. In the TFN network, the labels are classified by >=0. The same happens in the given demos(lstm). However, in early_fusion, the sentiment labels are classified by >0, so I wonder if the Zero(0) belongs to Positive or Negative? Also, should I submit both 7-class and Binary-class Prediction Files, or just one of them? Maybe a Regression? or any is OK? Thanks for your patience! Best wishes!

**Comment by Justin1904** [comment]
Hi! Sorry for the inconsistency. Here you should always treat 0 values as negative (i.e. setting the threshold as >0 instead of >=0). We'll correct the examples. Thanks for pointing that out!

**Comment by KuzmaNg** [comment]
Thank you so much! @Justin1904

**Comment by A2Zadeh** [comment]
0s are a bit tricky in sentiment. Some people consider positive some negative, some just ignore them. Each method has issues, for example if you ignore them in training during testing there will be zeros and you will be assigning them to positive or negative in a structured way. That is why I like regression for sentiment. When you hear a strong negative sentence it triggers a feeling that has a continuous nature rather than feeling that your -3 part of your brain is activated. My humble opinion. That is why we calculate everything on continuous outputs unless you provide classification labels yourself.

**Comment by KuzmaNg** [comment]
Thanks for your comments! @A2Zadeh
