### ISSUE TITLE
making my own input data (as MOSI)

### ISSUE THREAD

**Issue by amirim** [A2Zadeh/CMU-MultimodalDataSDK#23]
Hi, I want to make sentiment analysis for my input video (not of MOSI/MOSEI). Thus, first step would be (correct me if I'm wrong) to make the same input files/directories arrangement as MOSI in order to be able to train another [model](https://github.com/Justin1904/TensorFusionNetworks) that depends on CMU. Like MOSI, I can make my own features extraction with pyAudioAnalysis, Glove and FACET and generate the pickles. But I'm confused about the data format that CMU gets. For example for MOSI- just 9 .pkl files and MOSEI-11. so what do I need to generate? Another question is: for my purpose (training that model with my data), can I somehow skip using CMU? the only reason is maybe the alignment (I'm not familiar with P2FA), have I missed somethig here?

**Comment by Justin1904** [comment]
Hi, if you would like to use custom data, it's possible but requires a bit of more work. First of all you can download as an example the raw dataset files (let's say MOSI, because it's not too big and has a relatively complete set of features) as specified in section 3.7 in the README. There you can see how the basic formats of features are for the SDK. Just a reminder that the pickle files you are seeing are Dataset class objects, and we have went through the preprocessing and loading of the raw features files to get there, which in your case you'll have to do it from scratch (although SDK provide some functionalities that helps you do that). Basically, you'll need to have your data in the same format as the raw dataset files, and then you'll need to write another meta data configuration file, and then you can load and align your data using the SDK. We'll update the details for using custom data like how to write the meta data configuration file in the near future, but first I suggest you download the raw dataset files and see if your data can be put into that format.

**Comment by amirim** [comment]
which tool would you recommend for 'speech to text' in this case?
